image: python:3.8-bullseye

pages:
  script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends gettext python3-babel python3-pip git python3-inifile python3-dev python3-setuptools python3-venv python3-openssl python3-cryptography -y
    - pip3 install babel
    - pip3 install wheel
    - pip3 install lektor
    - rm -rf i18n
    - git clone --depth 1 --single-branch --branch=tbmanual-contentspot https://gitlab.torproject.org/tpo/translation.git i18n
    - git clone --depth 1 https://gitlab.torproject.org/tpo/web/lego.git lego
    - git submodule update --init --recursive --depth 1
    - rm -rf public
    - lektor build --output-path public && lektor build --output-path public && lektor build --output-path public
  artifacts:
    paths:
      - public
  only:
    - main
